baseurl = "/"
title = "Tobin Harding"
languageCode = "en-us"
theme = "hugo-theme-nix"

[params]
  Author = "Tobin Harding"
  GithubID = "tcharding"
  LinkedInID = "tobin-harding-9b1826124?trk=hp-identity-name"
  FacebookID = "profile.php?id=100010716374185"
  Name = "Tobin Harding"
  HeaderUsername = "tobin"
  HeaderHostname = "eros"
  Email = "me@tobin.cc"
  About = "Code, Climb, Roll, Breath"
  ProfilePicture = "selfy_hat.jpg"
  pygmentsuseclasses = false
  pygmentsStyle  = "monokai"
  pygmentscodefences = true
  
[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about-me"
  [[menu.header]]
    name = "books"
    weight = 0
    url = "/reading-list"
  [[menu.header]]
    name = "resume"
    weight = 0
    url = "/resume"
  [[menu.header]]
    name = "talks"
    weight = 0
    url = "/talks"
